### ISSUE TITLE
Plain message has been wrapped

### ISSUE THREAD

**Issue by jdd-software** [Tunaki/chatexchange#4]
Problem retrieving plain message after SE change of response

See:

https://chat.stackoverflow.com/transcript/message/38538245#38538245

The code that needs to be changed is here:

https://github.com/Tunaki/chatexchange/blob/master/src/main/java/fr/tunaki/stackoverflow/chat/Room.java#L504

It should be something similar to:

```
Elements ms = documentHistory.select (".message-source");
String plainContent = ms.get(0).ownText();
```

**Comment by Tunaki** [comment]
`.get(0)` would return the first line in the message history, which corresponds to the rendered output on screen. It would be the equivalent of `getContent()`. On the other hand, `getPlainContent()` returns the Markdown source ([javadoc](https://github.com/Tunaki/chatexchange/blob/95bfed767b93d161d7a1859e8f4cf820073a4c0e/src/main/java/fr/tunaki/stackoverflow/chat/Message.java#L54-L73), which should show in the IDE as well once downloaded). So we need to get the innertext of the newly added `span` here.
